name: Cloudflare Preview Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get branch name
        id: branch-name
        run: echo "branch=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT

      - name: Delete Cloudflare Pages deployments
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          PROJECT_NAME: bitgeese-web # Update with your Cloudflare Pages project name
          BRANCH_NAME: ${{ steps.branch-name.outputs.branch }}
        run: |
          if [ -z "$CLOUDFLARE_API_TOKEN" ] || [ -z "$CLOUDFLARE_ACCOUNT_ID" ]; then
            echo "⚠️ Cloudflare API token or Account ID not set. Skipping deployment cleanup."
            exit 0
          fi
          
          echo "🔍 Finding deployments for branch: $BRANCH_NAME"
          
          # Get deployments for the branch
          deployments=$(curl -s -X GET "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/pages/projects/${PROJECT_NAME}/deployments" \
            -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
            -H "Content-Type: application/json" | \
            jq -r --arg BRANCH "$BRANCH_NAME" '.result[] | select(.deployment_trigger.metadata.branch==$BRANCH) | .id')
          
          if [ -z "$deployments" ]; then
            echo "No deployments found for branch: $BRANCH_NAME"
            exit 0
          fi
          
          # Delete each deployment
          for deployment_id in $deployments; do
            echo "🗑️ Deleting deployment: $deployment_id"
            
            curl -s -X DELETE "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/pages/projects/${PROJECT_NAME}/deployments/${deployment_id}?force=true" \
              -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
              -H "Content-Type: application/json"
            
            echo "✅ Deleted deployment: $deployment_id"
          done 