name: Lighthouse Analysis

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lighthouse:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build site
        run: pnpm build

      - name: Run Lighthouse CI
        id: lhci
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            http://localhost:8080/
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 3
          configPath: './lighthouserc.cjs'
          serverBaseUrl: ${{ secrets.LHCI_SERVER_URL }}
          serverToken: ${{ secrets.LHCI_TOKEN }}
          before: |
            npm install -g serve
            serve -s dist -l 8080 &

      - name: Format Lighthouse score
        id: format_lighthouse_score
        uses: actions/github-script@v7
        with:
          script: |
            const links = ${{ steps.lhci.outputs.links }}
            const results = ${{ steps.lhci.outputs.manifest }}
            
            let summaryRows = [];
            let detailRows = [];
            
            for (const [urlIndex, url] of Object.entries(results)) {
              const urlName = url.url.replace(/^https?:\/\//, '');
              const summary = url.summary;
              
              summaryRows.push(`| ${urlName} | ${summary.performance} | ${summary.accessibility} | ${summary.best-practices} | ${summary.seo} |`);
              
              // Add details with emoji indicators
              const getScoreEmoji = (score) => {
                if (score >= 0.9) return '🟢';
                if (score >= 0.5) return '🟠';
                return '🔴';
              };
              
              detailRows.push(`### ${urlName}`);
              detailRows.push(`- Performance: ${getScoreEmoji(summary.performance)} ${Math.round(summary.performance * 100)}`);
              detailRows.push(`- Accessibility: ${getScoreEmoji(summary.accessibility)} ${Math.round(summary.accessibility * 100)}`);
              detailRows.push(`- Best Practices: ${getScoreEmoji(summary['best-practices'])} ${Math.round(summary['best-practices'] * 100)}`);
              detailRows.push(`- SEO: ${getScoreEmoji(summary.seo)} ${Math.round(summary.seo * 100)}`);
              detailRows.push('');
            }
            
            const report = links.lhr[0]; // Use the first report URL
            
            const comment = `## 🚦 Lighthouse Report

            ### Summary
            | URL | Performance | Accessibility | Best Practices | SEO |
            | --- | ----------- | ------------ | -------------- | --- |
            ${summaryRows.join('\n')}
            
            ### Details
            ${detailRows.join('\n')}
            
            [📊 View Full Report](${report})
            `;
            
            core.setOutput('comment', comment);

      - name: Add or update PR comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: lighthouse
          message: ${{ steps.format_lighthouse_score.outputs.comment }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 